version: '3.4'

networks:
  net:
    driver: bridge

volumes:
  nexus-data:

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    volumes:
      - 'nexus-data:/nexus-data'
    networks:
      - net
    ports:
      - "80:8081"


  nginx:
    image: nginx_nexus
    build:
      context: nginx
    container_name: nginx
    restart: always
    networks:
      - net
    ports:
      - "443:443"
    depends_on:
      - nexus
